name: secret_park_explorer
description: "Secret Park Explorer est une application interactive permettant de découvrir des lieux cachés et des points d’intérêt secrets dans un célèbre parc à thème en Europe. Explorez les différents secrets du parc, filtrez les lieux par catégorie, et obtenez des informations détaillées sur chaque endroit"
publish_to: "none"
version: 1.0.1 # à modifier pour les releases

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter
    google_maps_flutter: ^2.12.1
    image_picker: ^1.1.2
    shared_preferences: ^2.0.15
    path_provider: ^2.0.10
    url_launcher: ^6.1.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    flutter_launcher_icons: ^0.14.3

flutter_icons:
    android: true
    ios: false
    image_path: "assets/logoB.png"

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/markers.json
        - assets/logo.png
